<a href="https://colab.research.google.com/github/akamreez/newyorkcityfareprediction/blob/master/newyork_city_taxi_fare_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy pandas jovian opendatasets scikit-learn xgboost --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 952.6 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [2]:
import opendatasets as od
dataset_url = 'https://www.kaggle.com/c/new-york-city-taxi-fare-prediction/overview'

In [3]:
%%time
od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: amreezkhan
Your Kaggle Key: ··········


100%|██████████| 1.56G/1.56G [00:15<00:00, 108MB/s]



Extracting archive ./new-york-city-taxi-fare-prediction/new-york-city-taxi-fare-prediction.zip to ./new-york-city-taxi-fare-prediction
CPU times: user 42.6 s, sys: 11.1 s, total: 53.7 s
Wall time: 2min 5s


In [6]:
data_dir = './new-york-city-taxi-fare-prediction'

In [7]:
import pandas as pd
import random
sample_frac = 0.01

selected_cols = 'fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count'.split(',')
dtypes = {
    'fare_amount': 'float32',
    'pickup_longitude': 'float32',
    'pickup_latitude': 'float32',
    'dropoff_longitude': 'float32',
    'passenger_count': 'float32'
}

def skip_row(row_idx):
    if row_idx == 0:
        return False
    return random.random() > sample_frac

random.seed(42)
df = pd.read_csv(data_dir+"/train.csv",
                 usecols=selected_cols,
                 dtype=dtypes,
                 parse_dates=['pickup_datetime'],
                 skiprows=skip_row)

In [8]:
test_df = pd.read_csv(data_dir+'/test.csv', dtype=dtypes, parse_dates=['pickup_datetime'])

In [9]:
test_df

key           pickup_datetime  pickup_longitude  \
0     2015-01-27 13:08:24.0000002 2015-01-27 13:08:24+00:00        -73.973320   
1     2015-01-27 13:08:24.0000003 2015-01-27 13:08:24+00:00        -73.986862   
2     2011-10-08 11:53:44.0000002 2011-10-08 11:53:44+00:00        -73.982521   
3     2012-12-01 21:12:12.0000002 2012-12-01 21:12:12+00:00        -73.981163   
4     2012-12-01 21:12:12.0000003 2012-12-01 21:12:12+00:00        -73.966049   
...                           ...                       ...               ...   
9909  2015-05-10 12:37:51.0000002 2015-05-10 12:37:51+00:00        -73.968124   
9910  2015-01-12 17:05:51.0000001 2015-01-12 17:05:51+00:00        -73.945511   
9911  2015-04-19 20:44:15.0000001 2015-04-19 20:44:15+00:00        -73.991600   
9912  2015-01-31 01:05:19.0000005 2015-01-31 01:05:19+00:00        -73.985573   
9913  2015-01-18 14:06:23.0000006 2015-01-18 14:06:23+00:00        -73.988022   

      pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
0           40.763805         -73.981430         40.743835              1.0  
1           40.719383         -73.998886         40.739201              1.0  
2           40.751259         -73.979652         40.746139              1.0  
3           40.767807         -73.990448         40.751635              1.0  
4           40.789776         -73.988564         40.744427              1.0  
...               ...                ...               ...              ...  
9909        40.796997         -73.955643         40.780388              6.0  
9910        40.803600         -73.960213         40.776371              6.0  
9911        40.726608         -73.789742         40.647011              6.0  
9912        40.735432         -73.939178         40.801731              6.0  
9913        40.754070         -74.000282         40.759220              6.0  

[9914 rows x 7 columns]

In [10]:
test_df.describe()

pickup_longitude  pickup_latitude  dropoff_longitude  dropoff_latitude  \
count       9914.000000      9914.000000        9914.000000       9914.000000   
mean         -73.974716        40.751041         -73.973656         40.751743   
std            0.042774         0.033541           0.039072          0.035435   
min          -74.252190        40.573143         -74.263245         40.568973   
25%          -73.992500        40.736125         -73.991249         40.735254   
50%          -73.982327        40.753052         -73.980015         40.754065   
75%          -73.968012        40.767113         -73.964062         40.768757   
max          -72.986534        41.709557         -72.990967         41.696683   

       passenger_count  
count      9914.000000  
mean          1.671273  
std           1.278747  
min           1.000000  
25%           1.000000  
50%           1.000000  
75%           2.000000  
max           6.000000

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)
len(train_df), len(val_df)

(441960, 110490)

In [13]:
train_df = train_df.dropna()
val_df = val_df.dropna()

In [14]:
df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count'],
      dtype='object')

In [17]:
input_cols = ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'passenger_count']

In [15]:
target_col = 'fare_amount'

In [18]:
train_inputs = train_df[input_cols]
train_targets = train_df[target_col]
train_inputs

pickup_longitude  pickup_latitude  dropoff_longitude  \
353352        -73.993652        40.741543         -73.977974   
360070        -73.993805        40.724579         -73.993805   
372609        -73.959160        40.780750         -73.969116   
550895        -73.952187        40.783951         -73.978645   
444151        -73.977112        40.746834         -73.991104   
...                  ...              ...                ...   
110268        -73.987152        40.750633         -73.979073   
259178        -73.972656        40.764042         -74.013176   
365838        -73.991982        40.749767         -73.989845   
131932        -73.969055        40.761398         -73.990814   
121958        -73.983040        40.742142         -74.002510   

        dropoff_latitude  passenger_count  
353352         40.742352              4.0  
360070         40.724577              1.0  
372609         40.761231              1.0  
550895         40.772603              1.0  
444151         40.750403              2.0  
...                  ...              ...  
110268         40.763167              1.0  
259178         40.707841              2.0  
365838         40.720552              3.0  
131932         40.751327              1.0  
121958         40.727650              1.0  

[441960 rows x 5 columns]

In [19]:
train_targets

353352     6.0
360070     3.7
372609    10.0
550895     8.9
444151     7.3
          ... 
110268     9.3
259178    18.5
365838    10.1
131932    10.9
121958     9.5
Name: fare_amount, Length: 441960, dtype: float32

In [20]:
val_inputs = val_df[input_cols]
val_targets = val_df[target_col]
val_inputs

pickup_longitude  pickup_latitude  dropoff_longitude  \
15971         -73.995834        40.759190         -73.973679   
149839        -73.977386        40.738335         -73.976143   
515867        -73.983910        40.749470         -73.787170   
90307         -73.790794        40.643463         -73.972252   
287032        -73.976593        40.761944         -73.991463   
...                  ...              ...                ...   
467556        -73.968567        40.761238         -73.983406   
19482         -73.986725        40.755920         -73.985855   
186063          0.000000         0.000000           0.000000   
382260        -73.980057        40.760334         -73.872589   
18838         -73.955406        40.782417         -73.960434   

        dropoff_latitude  passenger_count  
15971          40.739086              1.0  
149839         40.751204              1.0  
515867         40.646643              1.0  
90307          40.690180              1.0  
287032         40.750309              2.0  
...                  ...              ...  
467556         40.750020              3.0  
19482          40.731170              1.0  
186063          0.000000              1.0  
382260         40.774298              1.0  
18838          40.767666              1.0  

[110490 rows x 5 columns]

In [21]:
test_inputs = test_df[input_cols]
test_inputs

pickup_longitude  pickup_latitude  dropoff_longitude  dropoff_latitude  \
0           -73.973320        40.763805         -73.981430         40.743835   
1           -73.986862        40.719383         -73.998886         40.739201   
2           -73.982521        40.751259         -73.979652         40.746139   
3           -73.981163        40.767807         -73.990448         40.751635   
4           -73.966049        40.789776         -73.988564         40.744427   
...                ...              ...                ...               ...   
9909        -73.968124        40.796997         -73.955643         40.780388   
9910        -73.945511        40.803600         -73.960213         40.776371   
9911        -73.991600        40.726608         -73.789742         40.647011   
9912        -73.985573        40.735432         -73.939178         40.801731   
9913        -73.988022        40.754070         -74.000282         40.759220   

      passenger_count  
0                 1.0  
1                 1.0  
2                 1.0  
3                 1.0  
4                 1.0  
...               ...  
9909              6.0  
9910              6.0  
9911              6.0  
9912              6.0  
9913              6.0  

[9914 rows x 5 columns]

In [22]:
from sklearn.linear_model import LinearRegression
linreg_model = LinearRegression()
linreg_model.fit(train_inputs, train_targets)

LinearRegression()

In [23]:
train_preds = linreg_model.predict(train_inputs)
train_preds

array([11.54623682, 11.28460949, 11.28413941, ..., 11.45891673,
       11.28428005, 11.28444733])

In [24]:
val_preds = linreg_model.predict(val_inputs)
val_preds

array([11.28432795, 11.28449549, 11.28478054, ..., 11.80449938,
       11.28443343, 11.28413233])

In [26]:
from sklearn.metrics import mean_squared_error

In [27]:
train_rmse = mean_squared_error(train_targets, train_preds, squared=False)
train_rmse

9.78863266989743

In [29]:
val_rmse = mean_squared_error(val_targets, val_preds, squared=False)
val_rmse

9.898088220645102

In [ ]:
# The linear regression model is off by $9.898, which isn't much better than simply predicting the average.

# This is mainly because the training data (geocoordinates) is not in a format that's useful for the model, and we're not using one of the most important columns: pickup date & time.

# However, now we have a baseline that our other models should ideally beat.

In [ ]:
#feature engineering

In [31]:
def add_dateparts(df, col):
    df[col + '_year'] = df[col].dt.year
    df[col + '_month'] = df[col].dt.month
    df[col + '_day'] = df[col].dt.day
    df[col + '_weekday'] = df[col].dt.weekday
    df[col + '_hour'] = df[col].dt.hour

In [32]:
add_dateparts(train_df, 'pickup_datetime')

In [33]:
add_dateparts(val_df, 'pickup_datetime')
add_dateparts(test_df, 'pickup_datetime')

In [34]:
import numpy as np

def haversine_np(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)

    All args must be of equal length.

    """
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2

    c = 2 * np.arcsin(np.sqrt(a))
    km = 6367 * c
    return km

In [35]:
def add_trip_distance(df):
    df['trip_distance'] = haversine_np(df['pickup_longitude'], df['pickup_latitude'], df['dropoff_longitude'], df['dropoff_latitude'])

In [36]:
add_trip_distance(val_df)

In [41]:
jfk_lonlat = -73.7781, 40.6413
lga_lonlat = -73.8740, 40.7769
ewr_lonlat = -74.1745, 40.6895
met_lonlat = -73.9632, 40.7794
wtc_lonlat = -74.0099, 40.7126

In [42]:
def add_landmark_dropoff_distance(df, landmark_name, landmark_lonlat):
    lon, lat = landmark_lonlat
    df[landmark_name + '_drop_distance'] = haversine_np(lon, lat, df['dropoff_longitude'], df['dropoff_latitude'])

In [43]:
%%time
for a_df in [train_df, val_df, test_df]:
    for name, lonlat in [('jfk', jfk_lonlat), ('lga', lga_lonlat), ('ewr', ewr_lonlat), ('met', met_lonlat), ('wtc', wtc_lonlat)]:
        add_landmark_dropoff_distance(a_df, name, lonlat)

CPU times: user 266 ms, sys: 66.6 ms, total: 332 ms
Wall time: 390 ms


In [50]:
add_trip_distance(train_df)
add_trip_distance(val_df)
add_trip_distance(test_df)

In [51]:
train_df.describe()

fare_amount  pickup_longitude  pickup_latitude  dropoff_longitude  \
count  441960.000000     441960.000000    441960.000000      441960.000000   
mean       11.354714        -72.498627        39.909996         -72.508141   
std         9.789793         11.795325         8.464263          12.398610   
min       -52.000000      -1183.362793     -3084.490234       -3356.729736   
25%         6.000000        -73.992027        40.734859         -73.991409   
50%         8.500000        -73.981819        40.752613         -73.980171   
75%        12.500000        -73.967186        40.767006         -73.963715   
max       400.000000       2420.209473       404.899994        2467.752686   

       dropoff_latitude  passenger_count  pickup_datetime_year  \
count     441960.000000    441960.000000         441960.000000   
mean          39.937865         1.684444           2011.740038   
std            9.857420         1.344170              1.857024   
min        -2073.150613         0.000000           2009.000000   
25%           40.733968         1.000000           2010.000000   
50%           40.753078         1.000000           2012.000000   
75%           40.768045         2.000000           2013.000000   
max         3351.403027       208.000000           2015.000000   

       pickup_datetime_month  pickup_datetime_day  pickup_datetime_weekday  \
count          441960.000000        441960.000000            441960.000000   
mean                6.263920            15.732492                 3.035813   
std                 3.434881             8.697374                 1.950033   
min                 1.000000             1.000000                 0.000000   
25%                 3.000000             8.000000                 1.000000   
50%                 6.000000            16.000000                 3.000000   
75%                 9.000000            23.000000                 5.000000   
max                12.000000            31.000000                 6.000000   

       pickup_datetime_hour  jfk_drop_distance  lga_drop_distance  \
count         441960.000000      441960.000000      441960.000000   
mean              13.506568         193.147978         182.365206   
std                6.517710        1223.614787        1226.672207   
min                0.000000           0.305535           0.116385   
25%                9.000000          20.535191           8.350965   
50%               14.000000          21.202076           9.575570   
75%               19.000000          21.948262          11.122069   
max               23.000000       15057.674834       15074.642961   

       ewr_drop_distance  met_drop_distance  wtc_drop_distance  trip_distance  
count      441960.000000      441960.000000      441960.000000  441960.000000  
mean          191.412330         177.416092         178.902096      19.751764  
std          1228.515208        1228.388658        1228.487258     371.299305  
min             0.129259           0.031095           0.009334       0.000000  
25%            16.502844           2.169888           3.642498       1.212450  
50%            18.016353           3.818017           5.559662       2.116230  
75%            19.953306           6.071750           7.814534       3.879673  
max         15074.714623       15077.613474       15072.109731   16913.444834

In [52]:
test_df.describe()

pickup_longitude  pickup_latitude  dropoff_longitude  dropoff_latitude  \
count       9914.000000      9914.000000        9914.000000       9914.000000   
mean         -73.974716        40.751041         -73.973656         40.751743   
std            0.042774         0.033541           0.039072          0.035435   
min          -74.252190        40.573143         -74.263245         40.568973   
25%          -73.992500        40.736125         -73.991249         40.735254   
50%          -73.982327        40.753052         -73.980015         40.754065   
75%          -73.968012        40.767113         -73.964062         40.768757   
max          -72.986534        41.709557         -72.990967         41.696683   

       passenger_count  pickup_datetime_year  pickup_datetime_month  \
count      9914.000000           9914.000000            9914.000000   
mean          1.671273           2011.815816               6.857979   
std           1.278747              1.803347               3.353272   
min           1.000000           2009.000000               1.000000   
25%           1.000000           2010.000000               4.000000   
50%           1.000000           2012.000000               7.000000   
75%           2.000000           2014.000000              10.000000   
max           6.000000           2015.000000              12.000000   

       pickup_datetime_day  pickup_datetime_weekday  pickup_datetime_hour  \
count          9914.000000              9914.000000           9914.000000   
mean             16.194170                 2.852834             13.467420   
std               8.838482                 1.994451              6.868584   
min               1.000000                 0.000000              0.000000   
25%               9.000000                 1.000000              8.000000   
50%              16.000000                 3.000000             15.000000   
75%              25.000000                 5.000000             19.000000   
max              31.000000                 6.000000             23.000000   

       jfk_drop_distance  lga_drop_distance  ewr_drop_distance  \
count        9914.000000        9914.000000        9914.000000   
mean           20.916707           9.675209          18.546655   
std             3.303942           3.295656           4.035818   
min             0.402057           0.285510           0.284706   
25%            20.513366           8.311562          16.520468   
50%            21.181394           9.477792          18.024364   
75%            21.909781          10.965471          19.880521   
max           134.497657         126.062486         149.400789   

       met_drop_distance  wtc_drop_distance  trip_distance  
count        9914.000000        9914.000000    9914.000000  
mean            4.512975           6.037621       3.433217  
std             4.018438           4.252537       3.969883  
min             0.085728           0.040386       0.000009  
25%             2.126326           3.669914       1.297281  
50%             3.698360           5.541418       2.215669  
75%             5.922760           7.757408       4.042928  
max           130.347048         138.619454      99.933359

In [53]:
def remove_outliers(df):
    return df[(df['fare_amount'] >= 1.) &
              (df['fare_amount'] <= 500.) &
              (df['pickup_longitude'] >= -75) &
              (df['pickup_longitude'] <= -72) &
              (df['dropoff_longitude'] >= -75) &
              (df['dropoff_longitude'] <= -72) &
              (df['pickup_latitude'] >= 40) &
              (df['pickup_latitude'] <= 42) &
              (df['dropoff_latitude'] >=40) &
              (df['dropoff_latitude'] <= 42) &
              (df['passenger_count'] >= 1) &
              (df['passenger_count'] <= 6)]

In [54]:
input_cols = ['pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_datetime_year', 'pickup_datetime_month', 'pickup_datetime_day',
       'pickup_datetime_weekday', 'pickup_datetime_hour', 'trip_distance',
       'jfk_drop_distance', 'lga_drop_distance', 'ewr_drop_distance',
       'met_drop_distance', 'wtc_drop_distance']

In [55]:
target_col = 'fare_amount'
train_inputs = train_df[input_cols]
train_targets = train_df[target_col]
val_inputs = val_df[input_cols]
val_targets = val_df[target_col]
test_inputs = test_df[input_cols]

In [56]:
def evaluate(model):
    train_preds = model.predict(train_inputs)
    train_rmse = mean_squared_error(train_targets, train_preds, squared=False)
    val_preds = model.predict(val_inputs)
    val_rmse = mean_squared_error(val_targets, val_preds, squared=False)
    return train_rmse, val_rmse, train_preds, val_preds

In [59]:
from sklearn.linear_model import Ridge
model1 = Ridge(random_state=42)
model1.fit(train_inputs, train_targets)

Ridge(random_state=42)

In [60]:
evaluate(model1)

(8.073475737378256,
 8.262912159729284,
 array([11.23632563,  8.83476719,  9.45270101, ..., 10.48299762,
         8.80257094, 11.30590234]),
 array([11.86444174,  8.03478304, 37.89042561, ...,  9.88983629,
        27.04323617, 10.40886035]))

In [62]:
# from xgboost import XGBRegressor
# model2 = XGBRegressor(random_state=42, n_jobs=-1, objective='reg:squarederror')

# model2.fit(train_inputs, train_targets)
from sklearn.ensemble import RandomForestRegressor

In [63]:
model2 = RandomForestRegressor(max_depth=10, n_jobs=-1, random_state=42, n_estimators=50)


In [ ]:

model2.fit(train_inputs, train_targets)

evaluate(model2)


# (3.597928386250033,
#  4.162749304500683,
#  array([ 7.04562027,  9.16841263,  9.10837664, ..., 10.3855101 ,
#          7.74169069, 10.38922928]),
#  array([12.53333721,  6.14758144, 47.32745299, ...,  8.33097815,
#         29.15652571,  8.2638333 ]))

In [65]:
xgb_model_final = XGBRegressor(objective='reg:squarederror', n_jobs=-1, random_state=42,
                               n_estimators=500, max_depth=5, learning_rate=0.1,
                               subsample=0.8, colsample_bytree=0.8)

In [ ]:
xgb_model_final.fit(train_inputs, train_targets)

In [ ]:
evaluate(xgb_model_final)

In [ ]:
# 4.21374,
#  4.1656484,
#  array([ 6.5733523,  7.7361407,  9.870613 , ..., 11.501726 ,  8.953172 ,
#         10.400705 ], dtype=float32),
#  array([14.024538 ,  6.142005 , 48.21192  , ...,  7.6997824, 30.115818 ,
#          8.906446 ], dtype=float32))